### ISSUE TITLE
JavaScript group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by yusufyusie** [yusufyusie/API-based-webapp#21]
https://github.com/yusufyusie/API-based-webapp/projects/1
**There are two members on this Javascript capstone project:-**

- [chudisoft Christopher Uduekwe](https://github.com/chudisoft) :- Student A
- [yusufyusie Yesuf Fenta](https://github.com/yusufyusie) :- Student B

**Comment by julie-ify** [comment]
## Hi @yusufyusie and @chudisoft,

Good job so far!

## Highlights!
- Descriptive Issue ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Kindly remove all Student C tasks from your Kanban. Since you are two in number, you should only have about 15 tasks.

- [ ] You have not assigned any of your tasks. Kindly choose who would be students A and B and assign your tasks based on that.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ridwanediallo** [comment]
# STATUS: APPROVED 🟢
## Hi team, 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done removing the extra cards and distributing the task between the team members.
- You successfully completed all the requirements.  🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
